name: dart_amqp
description: >
  A native dart AMQP client supporting version 0.9.1 of the AMQP protocol. It features an asynchronous API, pluggable authentication providers and TLS support.
version: 0.3.1
homepage: https://github.com/achilleasa/dart_amqp
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  async: ^2.10.0
  equatable: ^2.0.7
  logging: ^1.0.1
dev_dependencies:
  test: ^1.17.5
  mockito: ^5.0.9
  http: ^1.2.0
  xml: ^6.2.2
  lints: ^4.0.0
false_secrets:
  - test/lib/mocks/certs/*.pem
